export interface Game {
  id: string;
  name: string;
  emoji: string;
  description: string;
  category: "suspense" | "puzzle" | "reflex" | "high-risk";
  difficulty: "Easy" | "Medium" | "Hard" | "Extreme";
}

export const gamesList: Game[] = [
  // Suspense & Fast Reaction Games
  {
    id: "flip-game",
    name: "Flip Game",
    emoji: "⚡",
    description: "Classic heads or tails with animated coin flip",
    category: "suspense",
    difficulty: "Easy",
  },
  {
    id: "crash",
    name: "Crash",
    emoji: "💥",
    description: "Cash out before the multiplier crashes!",
    category: "suspense",
    difficulty: "Medium",
  },
  {
    id: "prediction-market",
    name: "Prediction Market",
    emoji: "⚖️",
    description: "Predict if crypto price goes up or down",
    category: "suspense",
    difficulty: "Medium",
  },
  {
    id: "dice-roll",
    name: "Dice Roll",
    emoji: "🔢",
    description: "Pick a number 1-6 and roll the dice",
    category: "suspense",
    difficulty: "Hard",
  },
  {
    id: "rock-paper-scissors",
    name: "Rock Paper Scissors",
    emoji: "✊",
    description: "Classic game against AI opponent",
    category: "suspense",
    difficulty: "Medium",
  },
  {
    id: "mini-jackpot",
    name: "Mini Jackpot",
    emoji: "🎰",
    description: "Match 3 digits to win the jackpot",
    category: "suspense",
    difficulty: "Hard",
  },
  {
    id: "color-blast",
    name: "Color Blast",
    emoji: "🎨",
    description: "Pick a color and spin the wheel",
    category: "suspense",
    difficulty: "Medium",
  },
  {
    id: "coin-duel",
    name: "Coin Duel",
    emoji: "🤺",
    description: "Duel against AI with coin flips",
    category: "suspense",
    difficulty: "Medium",
  },
  {
    id: "time-bomb",
    name: "Time Bomb",
    emoji: "💣",
    description: "Defuse the bomb at exactly the right moment",
    category: "reflex",
    difficulty: "Hard",
  },
  {
    id: "stack-coins",
    name: "Stack Coins",
    emoji: "🪙",
    description: "Stack falling coins to target height",
    category: "reflex",
    difficulty: "Medium",
  },

  // Puzzle/Decision Games
  {
    id: "odd-or-even",
    name: "Odd or Even",
    emoji: "🧠",
    description: "Guess if the number will be odd or even",
    category: "puzzle",
    difficulty: "Easy",
  },
  {
    id: "unlock-vault",
    name: "Unlock the Vault",
    emoji: "🔒",
    description: "Choose the vault with hidden treasure",
    category: "puzzle",
    difficulty: "Medium",
  },
  {
    id: "mystery-box",
    name: "Mystery Box",
    emoji: "📦",
    description: "Pick the box with the secret prize",
    category: "puzzle",
    difficulty: "Hard",
  },
  {
    id: "risk-or-hold",
    name: "Risk or Hold",
    emoji: "💼",
    description: "Double your winnings or cash out safe",
    category: "puzzle",
    difficulty: "Medium",
  },
  {
    id: "market-slide",
    name: "Market Slide",
    emoji: "📉",
    description: "Predict if BTC will dump in 5 seconds",
    category: "puzzle",
    difficulty: "Hard",
  },
  {
    id: "spy-flip",
    name: "Spy Flip",
    emoji: "🕵️",
    description: "Find the one honest coin among fakes",
    category: "puzzle",
    difficulty: "Hard",
  },
  {
    id: "precision-bet",
    name: "Precision Bet",
    emoji: "🎯",
    description: "Slide to guess the exact multiplier",
    category: "puzzle",
    difficulty: "Hard",
  },
  {
    id: "hot-cold",
    name: "Hot/Cold",
    emoji: "🔥",
    description: "Guess the number with hot/cold feedback",
    category: "puzzle",
    difficulty: "Medium",
  },

  // Reflex & Timing Games
  {
    id: "quick-tap",
    name: "QuickTap",
    emoji: "⚡",
    description: "Tap the green button before time runs out",
    category: "reflex",
    difficulty: "Hard",
  },
  {
    id: "tap-target",
    name: "Tap Target",
    emoji: "🎯",
    description: "Hit moving targets as fast as possible",
    category: "reflex",
    difficulty: "Hard",
  },
  {
    id: "block-break",
    name: "Block Break",
    emoji: "🧱",
    description: "Destroy falling blocks before they hit bottom",
    category: "reflex",
    difficulty: "Hard",
  },
  {
    id: "outrun-bot",
    name: "Outrun Bot",
    emoji: "🧍",
    description: "Tap fast to stay ahead of the AI",
    category: "reflex",
    difficulty: "Hard",
  },
  {
    id: "dodge-roll",
    name: "Dodge Roll",
    emoji: "🏃",
    description: "Navigate through moving obstacles",
    category: "reflex",
    difficulty: "Hard",
  },
  {
    id: "follow-path",
    name: "Follow Path",
    emoji: "🧭",
    description: "Trace the glowing path in 5 seconds",
    category: "reflex",
    difficulty: "Medium",
  },
  {
    id: "voice-spin",
    name: "Voice Spin",
    emoji: "🎤",
    description: "Simulate yelling to spin the coin",
    category: "reflex",
    difficulty: "Medium",
  },

  // Big Bet, High Risk Games
  {
    id: "red-envelope",
    name: "Red Envelope",
    emoji: "🧧",
    description: "Choose from 5 lucky red packets",
    category: "high-risk",
    difficulty: "Medium",
  },
  {
    id: "bank-run",
    name: "Bank Run",
    emoji: "🏦",
    description: "Cash out before the guards arrive",
    category: "high-risk",
    difficulty: "Hard",
  },
  {
    id: "guess-multiplier",
    name: "Guess Multiplier",
    emoji: "🧮",
    description: "Guess the closest multiplier to win big",
    category: "high-risk",
    difficulty: "Medium",
  },
  {
    id: "combo-picker",
    name: "Combo Picker",
    emoji: "🔢",
    description: "Pick the winning 3-number combination",
    category: "high-risk",
    difficulty: "Hard",
  },
  {
    id: "sudden-death",
    name: "Sudden Death",
    emoji: "🧨",
    description: "Win big or lose everything on one tap",
    category: "high-risk",
    difficulty: "Extreme",
  },
];
